apiVersion: 1

contactPoints:
  - orgId: 1
    name: Slack Alerts
    receivers:
      - uid: slack-notifier
        type: webhook
        settings:
          # Use ${ENV_VAR:-DEFAULT_VALUE} syntax
          url: "${SLACK_WEBHOOK_URL:-https://hooks.slack.com/services/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}"
