apiVersion: 1

contactPoints:
  - orgId: 1
    name: Slack Alerts
    receivers:
      - uid: slack-notifier
        type: slack
        settings:
          # Replace with your actual Slack Incoming Webhook URL
          url: "https://hooks.slack.com/services/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"
          recipient: "#daftarproupdatesmonitoring"
          username: "Grafana"
          mentionChannel: "here"
